runtime: java11
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: kotr-test@appspot.gserviceaccount.com
entrypoint: 'java -jar google-appengine-standard-1.0-SNAPSHOT-all.jar'


