runtime: java21
env: standard
instance_class: F1
handlers:
  - url: /.*
    script: this field is required, but ignored

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: kotr-test@appspot.gserviceaccount.com
entrypoint: 'java -jar com.list.synchronization-all.jar'
env_variables:
  BUCKET_NAME: kotr-test.appspot.com


